### ISSUE TITLE
error when using chain()

### ISSUE THREAD

**Issue by mofahead** [kennethreitz/delegator.py#12]
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux
>>> import delegator
>>> c = delegator.chain('fortune | cowsay')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/delegator.py", line 197, in chain
    commands = _expand_args(command)
  File "/usr/local/lib/python3.5/dist-packages/delegator.py", line 178, in _expand_args
    if isinstance(command, (str, unicode)):
NameError: name 'unicode' is not defined

**Comment by nateprewitt** [comment]
This is resolved in #13.
