### ISSUE TITLE
daemon.py "SyntaxError: invalid token." "os.umask(022)"  

### ISSUE THREAD

**Issue by feluxe** [kennethreitz/delegator.py#7]
I have a file ``test_delegator.py``:

    import delegator

    print('hello')
    delegator.run('ls')

If I run ``python -m mypackage.cli`` in a python3.6 venv, I get this error:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "/home/peter/myapp/mypackage/test_delegator.py", line 1, in <module>
        import delegator
      File "/home/peter/myapp/venv-myapp/lib/python3.6/site-packages/delegator.py", line 6, in <module>
        import daemon
      File "/home/peter/myapp/venv-myapp/lib/python3.6/site-packages/daemon.py", line 70
        os.umask(022)   # Don't allow others to write
                   ^
    SyntaxError: invalid token

Let me know if you need more info.

**Update**:

It looks like the *deamon* package is not Python3 compatible:

    $ python3.6                         

    Python 3.6.0 (default, Dec 24 2016, 06:35:36) 
    [GCC 4.8.4] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.umask(022)
      File "<stdin>", line 1
        os.umask(022)
                   ^
    SyntaxError: invalid token
    >>> 

Compared to python2.7

    $ python2.7

    Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
    [GCC 4.8.4] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.umask(022)
    18
    >>>

**Comment by kennethreitz** [comment]
fixed!
